### ISSUE TITLE
./build.sh is broken with a 404 error

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/compute-sabayon-image-builder#1]
sudo ./build.sh
Downloading Sabayon_Linux_15.09_amd64_SpinBase_tarball.tar.gz...
--2015-09-23 11:31:43--  http://dl.sabayon.org/iso/monthly/Sabayon_Linux_15.09_amd64_SpinBase_tarball.tar.gz
Resolving dl.sabayon.org (dl.sabayon.org)... 149.132.176.64
Connecting to dl.sabayon.org (dl.sabayon.org)|149.132.176.64|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://packages.sabayon.org/r/iso/monthly/Sabayon_Linux_15.09_amd64_SpinBase_tarball.tar.gz [following]
--2015-09-23 11:31:44--  http://packages.sabayon.org/r/iso/monthly/Sabayon_Linux_15.09_amd64_SpinBase_tarball.tar.gz
Resolving packages.sabayon.org (packages.sabayon.org)... 149.132.176.64
Reusing existing connection to dl.sabayon.org:80.
HTTP request sent, awaiting response... 302 Found
Location: https://packages.sabayon.org/r/iso/monthly/Sabayon_Linux_15.09_amd64_SpinBase_tarball.tar.gz [following]
--2015-09-23 11:31:44--  https://packages.sabayon.org/r/iso/monthly/Sabayon_Linux_15.09_amd64_SpinBase_tarball.tar.gz
Connecting to packages.sabayon.org (packages.sabayon.org)|149.132.176.64|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://mirrors-usa.go-parts.com/sabayon/iso/monthly/Sabayon_Linux_15.09_amd64_SpinBase_tarball.tar.gz [following]
--2015-09-23 11:31:45--  http://mirrors-usa.go-parts.com/sabayon/iso/monthly/Sabayon_Linux_15.09_amd64_SpinBase_tarball.tar.gz
Resolving mirrors-usa.go-parts.com (mirrors-usa.go-parts.com)... 192.240.106.18
Connecting to mirrors-usa.go-parts.com (mirrors-usa.go-parts.com)|192.240.106.18|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-09-23 11:31:46 ERROR 404: Not Found.

**Comment by lxnay** [comment]
Our push script had an issue with the upload of tarball files.
I have fixed the issue and now I am uploading the missing files.

Thanks for reporting.
